### ISSUE TITLE
app crashes after exit animation

### ISSUE THREAD

**Issue by rubinnellikunnathu** [takahirom/PreLollipopTransition#38]
Hai. first of of i liked this library very much and working awesome,
But my problem is "**UNFORTUNATELY , MY APPLICATION HAS STOPPED**" after exit transition.
My code is 

_first activity_

```
package com.ruben.myapplication;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import com.kogitune.activity_transition.ActivityTransitionLauncher;

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ImageView imageView = (ImageView) findViewById(R.id.imageview);
        imageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(MainActivity.this, Main2Activity.class);
                startActivity(intent);
                ActivityTransitionLauncher.with(MainActivity.this).from(view).launch(intent);
            }
        });

    }
}

```

_second activity_

```
package com.ruben.myapplication;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import com.kogitune.activity_transition.ActivityTransition;
import com.kogitune.activity_transition.ExitActivityTransition;


public class Main2Activity extends AppCompatActivity {
    private ExitActivityTransition exitTransition;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
        exitTransition = ActivityTransition.with(getIntent()).to(findViewById(R.id.imageview)).start(savedInstanceState);
    }

    @Override
    public void onBackPressed() {
        exitTransition.exit(this);
    }
}
```

_Logcat error Shows_

```
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.ruben.myapplication, PID: 12101
                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ruben.myapplication/com.ruben.myapplication.Main2Activity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2348)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5351)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
                                                                             at com.kogitune.activity_transition.core.TransitionData.<init>(TransitionData.java:36)
                                                                             at com.kogitune.activity_transition.core.TransitionAnimation.startAnimation(TransitionAnimation.java:27)
                                                                             at com.kogitune.activity_transition.ActivityTransition.start(ActivityTransition.java:51)
                                                                             at com.ruben.myapplication.Main2Activity.onCreate(Main2Activity.java:17)
                                                                             at android.app.Activity.performCreate(Activity.java:6012)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410) 
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1313) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5351) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742) 
```

**Can u pls help me as soon as possible ??**

**Comment by rubinnellikunnathu** [comment]
your code samples are not understandable, i hope it is due to some injection language like butterknife, how do i do it without butterknife, your sample also not building in android studio, it shows alot of errors.

**Comment by takahirom** [comment]
Thank you for reporting.
I will look that.
Please tell me support library version. And android gradle plugin version.

**Comment by rubinnellikunnathu** [comment]
Thank you for reply 

My Gradle is `classpath 'com.android.tools.build:gradle:2.1.3'`
and my support libraries are

```
 compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.android.support:cardview-v7:24.2.0'
    compile 'com.android.support:design:24.2.0'
    compile 'com.android.support:recyclerview-v7:24.2.0'
    compile 'com.android.support:gridlayout-v7:24.2.0'
    compile 'com.android.support:support-v4:24.2.0'
```

and compile SDK

```
compileSdkVersion 24
    buildToolsVersion "24.0.0"
    defaultConfig {
        applicationId "com.ruben.MyApplication"
        minSdkVersion 16
        targetSdkVersion 24
```

**Comment by takahirom** [comment]
It did not reproduce.
Please use updated version. 
compile 'com.kogitune:pre-lollipop-activity-transition:1.3.2'

**Comment by rubinnellikunnathu** [comment]
Thank you so much bro. now its working without any error.
